sudo: false
language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
cache: pip
env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
install:
  - pip install -U pip tox
script:
  - tox
