language: python
python:
  - "3.5"
sudo: false
env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install -U pip
  - pip install -U tox
script:
  - tox
